version: '3'
services:
  ovehub-ove-service-auth-base:
    image: ovehub/ove-service-auth-base:latest-unstable
    build: .
    ports:
      - "8080:8080"
    environment:
      GUNICORN_THREADS: "8"
      SERVICE_LOG_LEVEL: "debug"